### ISSUE TITLE
Map - issue with sf package

### ISSUE THREAD

**Issue by HFrouinMouy** [noaa-iea/r3-train#103]
Hello, I have an error message due to the sf package. 
> shelf(
+   NOAA-EDAB/ecodata,
+   sf)
Error: package or namespace load failed for ‘sf’:
 .onLoad failed in loadNamespace() for 'units', details:
  call: udunits_init(path)
  error: function 'Rcpp_precious_remove' not provided by package 'Rcpp'
I tried to uninstall and reinstall it. But I am still running with the same error. 
![image](https://user-images.githubusercontent.com/82541206/126185824-e9e356bf-d82d-4ad5-888a-3d338f2e79ba.png)

**Comment by adlienne** [comment]
Hi, I had the same problem, and spend some time googling how to solve it. I think what helped in the end was to install the package Rcpp and then update it (RStudio>Tools>Check for updates).
https://stackoverflow.com/questions/68416435/rcpp-package-doesnt-include-rcpp-precious-remove
(I also installed udunits2 as I read in another chat, but I think it was not needed).
Hope it helps, Adela

**Comment by bbest** [comment]
Thanks for chiming in @adlienne! I'll assume that got you going @HFrouinMouy and close this issue, but feel free to reopen with any further debug information after trying the suggestion.

**Comment by HFrouinMouy** [comment]
Hi Adela,

Thanks a lot - it worked! :) (I did not need udunits2).

@Ben Best ***@***.***> The lesson #map is missing sections 1.3 and
1.4 on https://noaa-iea.github.io/r3-train/map.html#group-by

Have a nice day,

Heloise
