### ISSUE TITLE
RStudio Git Push not working

### ISSUE THREAD

**Issue by bbest** [noaa-iea/r3-train#27]
from @diminera:

Dear Ben,

Thank you very much for your patience in advanced. 
I have been trying to fix my problem "to push" the changes but I didn´t succeded. I deleted everything and started from zero and the same...stays running but nothing occurs

Do you know what I am doing wrong?

![image](https://user-images.githubusercontent.com/2837257/122284356-5a4dbd00-cea2-11eb-941f-2e9e49ec63a7.png)

Regards,
Diana

**Comment by bbest** [comment]
Hi @diminera,

Hmmm... that's odd that you don't get any error message like it couldn't find the Git executable or had some specific problem with performing the `git push`. I'm on a Mac, not Windows, so have trouble reproducing your problem, but I would suggest simply **restarting RStudio** and trying again per [Chapter 13 Detect Git from RStudio | Happy Git and GitHub for the useR](https://happygitwithr.com/rstudio-see-git.html#tell-rstudio-where-to-find-git):

> **Restart RStudio if you make any changes**. Don’t make me stop this car again and restart RStudio for you in office hours. DO IT.
> 
> Do the steps at the top of the page to see if RStudio and Git are communicating now.
> 
> No joy?
> 
> - I’ve seen this help: With your Project open, go to Tools > Project Options.... If available, click on “Git/SVN” and select “Git” in the Version control system dropdown menu. Answer “yes” to the “Confirm New Git Repository” pop up. Answer “yes” to the “Confirm Restart RStudio” pop up.
> 
> - If you installed Git via GitHub for Windows, it is possible the Git executable is really well hidden. Get help or use one of our recommended methods of installing Git.
> 
> - Your PATH is probably not set up correctly and/or you should re-install Git and control/notice where it’s going. Read more in 14.
> 
> - Get our help.

**Comment by adlienne** [comment]
Hi Diana, I had the same problem, I found the solution here: https://stackoverflow.com/questions/1298499/git-push-not-send-changes-to-remote-git-repository

I entered the commands below into the terminal. With the git push, it suggested some options (I chose defualt) and then it asked me to enter my Git password in the web-browser, and my commits got updated online afterwards. Since then, the git push button works.

git stash
git pull
git add .
git commit -m "commit message"
git push

Cheers, Adela

**Comment by diminera** [comment]
Super Adlienne! 
It worked! Thanks a lot
Cheers,
Diana

**Comment by DylanMG** [comment]
I also had this issue. 
Thanks for sorting it out Adela!

**Comment by bbest** [comment]
Excellent! Thank you @adlienne for providing the super helpful solution. This is the most common pattern of problem solving: googling an error message and ending up on StackOverflow with the solution.

I hadn't seen [`git stash`](https://git-scm.com/docs/git-stash) before. 

And thank you @diminera and @DylanMG for checking the issues for the fix.

This is the beauty of open-source development! We help each other out :)
