### ISSUE TITLE
Fatal error when attempting to commit

### ISSUE THREAD

**Issue by cnpaterson** [noaa-iea/r3-train#34]
I am having issues with committing from RStudio. I have managed to work around it (I'm not sure what I did) but the error has returned. When trying to commit a change for 1.10 (which I don't think is the issue you wanted us to create) from RStudio I get the following: 

```
#fatal: Unable to create 'C:/Users/corinne.paterson/Documents/R3_course/R3-exercises/.git/index.lock': File exists.

Another git process seems to be running in this repository, e.g.
an editor opened by 'git commit'. Please make sure all processes
are terminated then try again. If it still fails, a git process
may have crashed in this repository earlier:
remove the file manually to continue.
```

The only things I have open are one instance of RStudio and my repo on GitHub. I am not sure what else would be using the Git process. Are you aware of what the issue might be?

I am also having issues with being able to stage items and an extreme slow down of RStudio that is sometimes fixed after closing RStudio once, but sometimes requires more. I have tried to troubleshoot those issues, but have found that they are just problems with RStudio and Git that are well documents but do not have solutions. Is it possible this is what is hanging up my commit?

**Comment by sarah-friesen** [comment]
I was having a similar problem but eventually got it to work after multiple times. I'm not sure what changed so I'm curious to hear what Ben's answer is!

**Comment by bbest** [comment]
Hi @cnpaterson,

Please try to close RStudio. Then open Rstudio again from Windows Explorer in `C:/Users/corinne.paterson/Documents/R3_course/R3-exercises/` by double-clicking on the `R3-exercises.Rproj` file. (You probably won't see the Rproj file extension, but the file should have an RStudio icon). Then try again.

If you get the same error, do  you have another program open like Github Desktop which might create the lock or when you say you have the "repo on GitHub" open do you simply mean in your web browser?

If you're still stuck, then you can open the **Terminal** pane from within RStudio and simply run the following command to delete the lock file:

```bash
# remove the lock file
rm .git/index.lock

# if that doesn't work, try to force it
rm -f .git/index.lock

# if that doesn't work, force it as super user
sudo rm -f .git/index.lock
```

Then try again.

**Comment by cnpaterson** [comment]
Hi @bbest 

Opening the project from the .Rproj file did not work for me. The only things running on my PC were RStudio and Chrome. I also attempted to use the commands for Terminal in RStudio. Ultimately I was able to commit by manually deleting the index.lock file from the hidden git folder and then restating RStudio from the project file however, I encounter the same error when attempting to pull from my GitHub repo in the next step. It seems very impractical to go in and manually delete the file from File Explorer every time.

**Comment by ajanefmc** [comment]
I opened the .Rproj file directly from the explorer, but the rm command does not work.
![image](https://user-images.githubusercontent.com/86071050/122804096-7633d300-d295-11eb-9872-07cc38c6fc04.png)

**Comment by cnpaterson** [comment]
@ajanefmc I had the same problem and was able to get the commands to be recognized by add git before rm git/index.lock
however, it did not recognize sudo.

**Comment by 7yl4r** [comment]
> I opened the .Rproj file directly from the explorer, but the rm command does not work.

`rm` is a linux (& mac) command. The windows analogue is `del`, so use `del .git/index.lock` instead.

`rm` and `del` both just delete a file though, so however you want to deleted that `.git/index.lock` should work.

**Comment by lavallef** [comment]
Hi Ben, 

I'm trying to push, but I am getting this error. I am able to pull fine. Looks like a permission issue?

![git commit issue](https://user-images.githubusercontent.com/46360852/122819972-f35c4980-d28f-11eb-8c5c-9d3c6885e957.PNG)

Thanks,
Flo

**Comment by 7yl4r** [comment]
> Hi Ben,
> 
> I'm trying to push, but I am getting this error. I am able to pull fine. Looks like a permission issue?
> 
> ![git commit issue](https://user-images.githubusercontent.com/46360852/122819972-f35c4980-d28f-11eb-8c5c-9d3c6885e957.PNG)
> 
> Thanks,
> Flo

This looks like something you should open a new issue for. You are trying to push to ben's repo instead of your own. This means you didn't fork properly. There are a few ways to fix this but the easiest is probably to start over and be sure you clone your account's fork instead of Ben's.

**Comment by bbest** [comment]
Yes, thanks so much @7yl4r!

I started a new separate issue [git push error - remote: Permission to bbest/r3-exercises.git denied #62](https://github.com/noaa-iea/r3-train/issues/62) for the most recent issue above.

So the updated instructions when experiencing an error like this:

```
#fatal: Unable to create '.git/index.lock': File exists.
```
are specific to the operating system...

### Mac

On a Mac machine:

```bash
# remove the lock file
rm .git/index.lock

# if that doesn't work, try to force it
rm -f .git/index.lock

# if that doesn't work, force it as super user
sudo rm -f .git/index.lock
```

### Windows

On a Windows machine:

```bash
# delete the lock file
del .git/index.lock

# if that doesn't work, try to force it
del /f .git/index.lock
```

**Comment by lavallef** [comment]
@7yl4r  and @bbest  Ah yes, that was a silly mistake on my part! Thanks for the quick response :)

**Comment by cnpaterson** [comment]
@bbest The windows commands worked for me when I started the whole exercise again. I am also having issues with being able to stage my files to commit so it is taking a long time for me to complete basic exercises.

**Comment by adlienne** [comment]
Hi, the error of @cnpaterson occurs when switching from rdm-website to main, because a file is staged in rdm-website (or in main) but not commited. Unstagging the file help clean the error, and switch between the branch and main.
