### ISSUE TITLE
Unable to complete Push

### ISSUE THREAD

**Issue by KayleeSmit** [noaa-iea/r3-train#44]
Hi Ben,
I have completed "all" the steps up to section 1.8, but I was having an issue with the Push command. I eventually skipped this step in section 1.5 and continued to section 1.8. But now I am unable to fully complete the Roster in section 1.8: Once I added my details to the csv file, I saved it and made a commit (" + KayleeSmit"), but then the Push is not able to complete in RStudio, it just continues indefinitely (it seems like another participant had the same issue, but I have not been able to resolve it). Thus I am not able to "contribute" to the forked branch and continue to make a pull request.
Please can you help me. I am so close :)

**Comment by 7yl4r** [comment]
If you can open the git command line then it may give you more information about what is happening. Open up the terminal and then the command should be `git commit -a -m "add Kaylee Smit to roster"`

That is `git commit`, `--all` files, commit `--message` is "add Kaylee Smit to roster".

**Comment by bbest** [comment]
Yes, reporting back with the entirety of messages you get back from @7yl4r's suggested command in RStudio's **Terminal** would be most helpful along with these:

```bash
git commit -a -m "add Kaylee Smit to roster"
git push
git status
```

**Comment by KayleeSmit** [comment]
Thanks very much 7yl4r and Ben, it worked!! Phew
Appreciate the input and the help
