### ISSUE TITLE
`fatal: unable to access` https://github.com/OWNER/REPO.git `routines:ssl3_get_record:wrong version number`

### ISSUE THREAD

**Issue by JuliaCoates** [noaa-iea/r3-train#68]
When Creating a new Project and using RStudio's git clone, I got this error:

```
>>> C:/Users/jcoates/AppData/Local/Programs/Git/bin/git.exe clone --progress https://github.com/JuliaCoates/r3-exercises.git r3-exercises
Cloning into 'r3-exercises'...
fatal: unable to access 'https://github.com/JuliaCoates/r3-exercises.git/': error:1408F10B:SSL routines:ssl3_get_record:wrong version number
```

**Comment by JuliaCoates** [comment]
```
>>> C:/Users/jcoates/AppData/Local/Programs/Git/bin/git.exe clone --progress https://github.com/JuliaCoates/r3-exercises.git r3-exercises
Cloning into 'r3-exercises'...
fatal: unable to access 'https://github.com/JuliaCoates/r3-exercises.git/': error:1408F10B:SSL routines:ssl3_get_record:wrong version `number```
```

**Comment by JuliaCoates** [comment]
```
C:\Users\jcoates\Documents>git config --list
diff.astextplain.textconv=astextplain
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
http.sslbackend=openssl
http.sslcainfo=C:/Users/jcoates/AppData/Local/Programs/Git/mingw64/ssl/certs/ca-bundle.crt
core.autocrlf=true
core.fscache=true
core.symlinks=false
pull.rebase=false
credential.helper=manager-core
credential.https://dev.azure.com.usehttppath=true
init.defaultbranch=master
user.name=JuliaCoates

C:\Users\jcoates\Documents>
```

**Comment by bbest** [comment]
Hi @JuliaCoates,

Please try running the git clone with verbose options from RStudio Terminal (instead of with New Project):

```
cd C:\Users\jcoates\Documents
git clone --progress --verbose https://github.com/JuliaCoates/r3-exercises.git
```

**Comment by bbest** [comment]
Try in **Terminal**:

```
curl -vhttps://github.com/JuliaCoates/r3-exercises.git
```

**Comment by JuliaCoates** [comment]
```

C:\Users\jcoates\Documents>curl -v https://github.com/JuliaCoates/r3-exercises.git
*   Trying 192.30.255.113...
* TCP_NODELAY set
* Connected to github.com (192.30.255.113) port 443 (#0)
* schannel: SSL/TLS connection with github.com port 443 (step 1/3)
* schannel: checking server certificate revocation
* schannel: sending initial handshake data: sending 181 bytes...
* schannel: sent initial handshake data: sent 181 bytes
* schannel: SSL/TLS connection with github.com port 443 (step 2/3)
* schannel: failed to receive handshake, need more data
* schannel: SSL/TLS connection with github.com port 443 (step 2/3)
* schannel: encrypted data got 1016
* schannel: encrypted data buffer: offset 1016 length 4096
* schannel: next InitializeSecurityContext failed: SEC_E_INVALID_TOKEN (0x80090308) - The token supplied to the function is invalid
* Closing connection 0
* schannel: shutting down SSL/TLS connection with github.com port 443
* schannel: clear security context handle
curl: (35) schannel: next InitializeSecurityContext failed: SEC_E_INVALID_TOKEN (0x80090308) - The token supplied to the function is invalid

C:\Users\jcoates\Documents>
```

**Comment by bbest** [comment]
windows 10 enterprise 20h2 on CA DFW

**Comment by bbest** [comment]
Trying New Project with git URL of SSH: git@github.com:JuliaCoates/r3-exercises.git

**Comment by JuliaCoates** [comment]
![RStudio SSH](https://user-images.githubusercontent.com/77514227/122968992-febb7d80-d340-11eb-8114-8398480883cb.png)

**Comment by bbest** [comment]
Ok @JuliaCoates, based on this other issue [Error: Fatal: unable to access 'https://github.com/xxx.git/': schannel: The revocation function was unable to check revocation for the certificate. · Issue #3889 · desktop/desktop](https://github.com/desktop/desktop/issues/3889), can you please try this in **Terminal**:

```bash
# turn off SSL verification
git config --global http.sslVerify false

# download git repo
git clone https://github.com/JuliaCoates/r3-exercises.git
```

**Comment by bbest** [comment]
Ok @JuliaCoates, based on this other issue [Error: Fatal: unable to access 'https://github.com/xxx.git/': schannel: The revocation function was unable to check revocation for the certificate. · Issue #3889 · desktop/desktop](https://github.com/desktop/desktop/issues/3889), can you please try this in **Terminal**:

## Method 1: older SSL method

```bash
# revert to older form of secure socket layer
git config --global http.sslBackend "openssl"

# download git repo
git clone https://github.com/JuliaCoates/r3-exercises.git
```

## Method 2: turn off SSL verification

If Method 1 doesn't work, then try this 2nd method:

```bash
# turn off SSL verification
git config --global http.sslVerify false

# download git repo
git clone https://github.com/JuliaCoates/r3-exercises.git
```

**Comment by JuliaCoates** [comment]
```
C:\Users\jcoates\Documents># download git repo
'#' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\jcoates\Documents>
C:\Users\jcoates\Documents>git clone https://github.com/JuliaCoates/r3-exercises.git
Cloning into 'r3-exercises'...
fatal: unable to access 'https://github.com/JuliaCoates/r3-exercises.git/': error:1408F10B:SSL routines:ssl3_get_record:wrong version number

C:\Users\jcoates\Documents># turn off SSL verification
'#' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\jcoates\Documents>
C:\Users\jcoates\Documents>git config --global http.sslVerify false

C:\Users\jcoates\Documents>
C:\Users\jcoates\Documents>
C:\Users\jcoates\Documents>
C:\Users\jcoates\Documents># download git repo
'#' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\jcoates\Documents>
C:\Users\jcoates\Documents>git clone https://github.com/JuliaCoates/r3-exercises.git
Cloning into 'r3-exercises'...
fatal: unable to access 'https://github.com/JuliaCoates/r3-exercises.git/': error:1408F10B:SSL routines:ssl3_get_record:wrong version number

C:\Users\jcoates\Documents>
```

**Comment by bbest** [comment]
Hi @JuliaCoates ,

Did you try running **Method 1: older SSL method**?

```bash
git config --global http.sslBackend "openssl"
git clone https://github.com/JuliaCoates/r3-exercises.git
```

I don't see it in the **Terminal** output from above. (Please skip running the commented lines that begin with `#`)

**Comment by JuliaCoates** [comment]
C:\Users\jcoates\Documents>git config --global http.sslBackend "openssl"

C:\Users\jcoates\Documents>git clone https://github.com/JuliaCoates/r3-exercises.git
Cloning into 'r3-exercises'...
fatal: unable to access 'https://github.com/JuliaCoates/r3-exercises.git/': error:1408F10B:SSL routines:ssl3_get_record:wrong version number

C:\Users\jcoates\Documents>

**Comment by bbest** [comment]
Hmm... are you able to install [microsoft/Git-Credential-Manager-for-Windows](https://github.com/microsoft/Git-Credential-Manager-for-Windows/releases/tag/1.20.0)?

Then use the path to wherever that `git.exe` is installed to try `git.exe clone` again.

**Comment by JuliaCoates** [comment]
Looks like I need administrator privileges for that.  I'll see if I can get in touch with IT.

**Comment by JuliaCoates** [comment]
Got the Git Credential Manager installed

**Comment by bbest** [comment]
Ok, is it working now?

**Comment by JuliaCoates** [comment]
>>> C:/Program Files/Git/bin/git.exe clone --progress https://github.com/JuliaCoates/r3-exercises.git r3-exercises
Cloning into 'r3-exercises'...
fatal: unable to access 'https://github.com/JuliaCoates/r3-exercises.git/': error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol

**Comment by bbest** [comment]
Ah that's too bad. Well I have exhausted all the reasonable possible fixes I can find. 

Looks like there's something funky with this government issued laptop from California Department of Fish and Wildlife. I'm not sure if it's the software or proxy server or both.

Please use a different machine or [rstudio.cloud](https://rstudio.cloud/) per [Setup](https://noaa-iea.github.io/r3-train/setup.html) suggestion.

**Comment by JuliaCoates** [comment]
OK thanks.  I'll look at the rstudio.cloud section in the Setup.  I've run into issues working in the cloud too!
