### ISSUE TITLE
`git push` hangs indefinitely

### ISSUE THREAD

**Issue by bbest** [noaa-iea/r3-train#70]
Working with @ajanefmc:

<img width="494" alt="Screen Shot 2021-06-22 at 4 41 07 PM" src="https://user-images.githubusercontent.com/2837257/123013240-b28c2f80-d378-11eb-89fe-2aac1a7317e8.png">

```
C:/Users/aapplegate/AppData/Local/Programs/Git/bin/git.exe push origin HEAD:refs/heads/main
```

**Comment by bbest** [comment]
Let's see what version of git you have?

```
C:/Users/aapplegate/AppData/Local/Programs/Git/bin/git.exe --version
```

**Comment by bbest** [comment]
Versions:
- RStudio 1.4.1106
- R: 4.0.3
- git: 2.32

**Comment by bbest** [comment]
Let's try to push with verbosity:

```sh
C:/Users/aapplegate/AppData/Local/Programs/Git/bin/git.exe push --verbose
```

**Comment by ajanefmc** [comment]
C:\Users\aapplegate\Documents\Training\r3-exercises>C:/Users/aapplegate/AppData/Local/Programs/Git/bin/git.exe push --verbose
Pushing to https://github.com/ajanefmc/r3-exercises/
Select an authentication method for 'https://github.com/':
  1. Web browser (default)
  2. Personal access token
option (enter for default):

**Comment by bbest** [comment]
<img width="290" alt="Screen Shot 2021-06-22 at 4 54 44 PM" src="https://user-images.githubusercontent.com/2837257/123014206-8ec9e900-d37a-11eb-9510-6a6ed34a5327.png">

<img width="203" alt="Screen Shot 2021-06-22 at 4 55 07 PM" src="https://user-images.githubusercontent.com/2837257/123014230-9ab5ab00-d37a-11eb-845e-0f19250556fb.png">

**Comment by bbest** [comment]
The problem was that the `git push` needed to get authorization, but wasn't receiving a response, so we:

1. Executed `git push` from the RStudio **Terminal**
2. Respond to prompt with option **1. Web browser (default)**
3. Web **browser**opens and clicked on **Authorize GitCredentialsManager**, then enter **password**, even if already logged into Github with your web browser.
4. Return to **RStudio** to see results of the `git push`

**Comment by bbest** [comment]
Working with Valentina @up201910412, we got her [r3-exercises](https://github.com/up201910412/r3-exercises) to push from her PC to Github using this command in **Terminal**:


```sh
"C:/Program Files/Git/mingw64/bin/git.exe" push --verbose
```
