### ISSUE TITLE
Commit changes not working?

### ISSUE THREAD

**Issue by ajanefmc** [noaa-iea/r3-train#85]
I am unsure about this issue and whether the modified local files need to be pushed, or something else has to happen.

When I commit and push files, git tells me everything is up to date.
![image](https://user-images.githubusercontent.com/86071050/123656823-40936a80-d7fe-11eb-9637-871db61ce5a8.png)

Yet when I look under the git tab, I still see lots of files?
![image](https://user-images.githubusercontent.com/86071050/123656988-6456b080-d7fe-11eb-834b-3c6e1a48ba89.png)

When I executed this step before, it seemed that the files listed under the git tab disappeared, but not this time.

If I am missing a step, please give me a clue.  TIA.

**Comment by bbest** [comment]
Looks like you have not ticked boxes next to changed files before executing **Commit**, then **Push** .

You can select multiple with click + Shift for all since last click or click + Ctrl to toggle individually

**Comment by ajanefmc** [comment]
I'm just not getting this part - even reviewing the video again.  I have repos, but when I commit changes and push, the local files do not show up in the repo or branch and I get this message:
![image](https://user-images.githubusercontent.com/86071050/124027428-de369780-d9c0-11eb-8e4b-3bdb403781ac.png)

**Comment by MarcioFCMartins** [comment]
Try doing what the error message suggests:

1. From the terminal, run `git pull` to update your local repo 
2. Add all your local files to the list to commit with `git add *` or by ticking the boxes in RSTUDIO
3. Now try committing and pushing

**Comment by bbest** [comment]
Thank you @MarcioFCMartins! Yes, @ajanefmc please simply try to **Pull** before you **Push** per the error message
