### ISSUE TITLE
Unable to Knit at 2.2.2 due to error

### ISSUE THREAD

**Issue by cnpaterson** [noaa-iea/r3-train#89]
I am having an issue with Knit from step 2.2.2 onward in the Manipulate exercise. I am copying the code from the Manipulate exercise page and pasting it into my own R Markdown file. And I am able to run the code from R Markdown (for this and all following steps) but I am unable to knit any of the steps.

Below is my input and the table I can generate in R Markdown:
![exercise2-rmarkdowninput](https://user-images.githubusercontent.com/85887224/123681030-ecdd4d00-d80e-11eb-9876-641bcca82335.jpg)
![exercise2-rmarkdowntableoutput](https://user-images.githubusercontent.com/85887224/123681045-f070d400-d80e-11eb-91d9-6341bc4f47c7.jpg)

And this is the error I get. 
![exercise2-rmarkdown_knit_error](https://user-images.githubusercontent.com/85887224/123681073-f961a580-d80e-11eb-8495-40047b1fcaf2.jpg)

So far I have not been able to diagnose the issue with the code due to my limited knowledge of R. Of note, I am running R 3.6.2.

**Comment by bbest** [comment]
That is an old version of R. Please update to the latest R and RStudio per [Setup](https://noaa-iea.github.io/r3-train/setup.html), along with **Update** to latest in **Packages** pane.

The error message above from the screenshot is:

```
Error: Problem with mutate()
i `time - as.Date(substr(time, 1, 10))`.
x character string is not in a standard unambiguous format
```

I can see from your [manipulate.rmd#L51-L58](https://github.com/bbest/R3-exercises-1/blob/4f8b881e02de4632b9f99d97e4dcb86782b6fd9c/manipulate.rmd#L51-L58) that some reason these critical lines are commented out to  properly read in the file (vs only using earlier improper read of csv containing two header rows):

```r
# read csv by skipping first two lines, so no header. Do this since data has two lines of header and we don't want the second line of header to be counted as a row in the table.
#d <- read.csv(csv, skip=2, header=FALSE)
# show the data frame
#d
# update data frame to original column names
#names(d) <- names(read.csv(csv))
```

I was able to successfully knit your `manipulate.rmd` by simply uncommenting these lines:


```r
# read csv by skipping first two lines, so no header. Do this since data has two lines of header and we don't want the second line of header to be counted as a row in the table.
d <- read.csv(csv, skip=2, header=FALSE)
# show the data frame
#d
# update data frame to original column names
names(d) <- names(read.csv(csv))
```

**Comment by cnpaterson** [comment]
Thank you @bbest !

As I suspected, it was my own error and not something with the code/version of R.

Unfortunately, a package critical for my work does not run in the newest version of R so I have to use an older version.
