### ISSUE TITLE
cciea online table is missing from erdap; change URL

### ISSUE THREAD

**Issue by ajanefmc** [noaa-iea/r3-train#96]
The instructions for section 2.1.2 in the training Rmd (https://noaa-iea.github.io/r3-train/manipulate.html) is not working now.

https://oceanview.pfeg.noaa.gov/services now takes you to this URL to access the ERDAP files: https://coastwatch.pfeg.noaa.gov/erddap/index.html.

But doing a full text search on "cciea" does returns no results: https://coastwatch.pfeg.noaa.gov/erddap/search/index.html?page=1&itemsPerPage=1000&searchFor=CCIEA+Anthropogenic+Drivers

Listing all data sets and searching the html for "cciea" also returns no results ":https://coastwatch.pfeg.noaa.gov/erddap/info/index.html?page=1&itemsPerPage=1000"

It appears that the CSV file is available here: https://github.com/noaa-iea/r3-train/blob/master/data/cciea_AC.csv

But the instructions in section 2.1.2 do not handle this file correctly:
# set variables
#csv_url  <- "https://oceanview.pfeg.noaa.gov/erddap/tabledap/cciea_AC.csv"
csv_url <- "https://github.com/noaa-iea/r3-train/blob/master/data/cciea_AC.csv"

dir_data <- "data"

# derived variables
csv <- file.path(dir_data, basename(csv_url))

# create directory
dir.create(dir_data)

# download file
download.file(csv_url, csv)

### Read table `read.csv()`
# read csv by skipping first two lines, so no header
d <- read.csv(csv, skip = 2, header = FALSE)
# update data frame to original column names
names(d) <- names(read.csv(csv))

Instead I get this after executing the above code in R:
str(d)
'data.frame':	405 obs. of  1 variable:
 $ X..DOCTYPE.html.: chr  "<!DOCTYPE html>" "<html lang=en data-color-mode=auto data-light-theme=light data-dark-theme=dark>" "  <head>" "    <meta charset=utf-8>" ...

Could someone update and correct the code in Section 2.1.2 and the Manipulate lesson so that the data can be re-processed in R.  I did not save the data set locally when I first worked with the lessons.

TIA.

**Comment by bbest** [comment]
Hi @ajanefmc,

There was some funk with the ERDDAP server https://oceanview.pfeg.noaa.gov/erddap (NOTE that is different from the other one you mention https://coastwatch.pfeg.noaa.gov/erddap).

I've added to [2.1.3 Download CSV - Manipulate](https://noaa-iea.github.io/r3-train/manipulate.html#213_Download_CSV) a comment with an alternate URL if the ERDDAP server is down:

```r
# set variables
csv_url  <- "https://oceanview.pfeg.noaa.gov/erddap/tabledap/cciea_AC.csv"
# if ERDDAP server down (Error in download.file) with URL above, use this:
#    csv_url <- "https://raw.githubusercontent.com/noaa-iea/r3-train/master/data/cciea_AC.csv"
```

So running it like so, should get you going:

```r
# set variables
#csv_url  <- "https://oceanview.pfeg.noaa.gov/erddap/tabledap/cciea_AC.csv"
# if ERDDAP server down (Error in download.file) with URL above, use this:
csv_url <- "https://raw.githubusercontent.com/noaa-iea/r3-train/master/data/cciea_AC.csv"
```
